name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Move govuk framework to templates/
        run: mv node_modules/govuk-frontend/govuk/ templates/

      - name: Build
        run: cd templates && node render.js

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1